name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x  # або будь-яка стабільна версія ю

      - name: Set Environment Variables
        run: |
          echo "PROCESSOR_ARCHITECTURE=AMD64" >> $GITHUB_ENV
          echo "MSBUILDDISABLENODEREUSE=1" >> $GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore modul.sln

      - name: Build project
        run: dotnet build modul.sln --configuration Release --no-restore -p:Platform="Any CPU"

      - name: Run unit tests
        run: dotnet test --no-restore --verbosity normal
        
  static_analysis:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.201

      - name: Install static analysis tools
        run: dotnet tool install --global dotnet-format

      - name: Run static code analysis
        run: dotnet format --verify-no-changes || true

  merge_check:
    needs: [build_and_test, static_analysis]
    runs-on: ubuntu-latest
    steps:
      - name: Ensure all checks passed before merging
        run: echo "All checks passed!"
