name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.201

      - name: Check .NET SDKs
        run: dotnet --list-sdks

      - name: Check MSBuild Version
        run: dotnet msbuild /version

      - name: Check if solution exists
        run: |
          if (-Not (Test-Path "modul.sln")) {
            Write-Error "Solution file not found!"
            exit 1
          }

      - name: Restore dependencies
        run: dotnet restore modul.sln

      - name: Build project
        run: dotnet build modul.sln --configuration Release --no-restore


  static_analysis:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.201

      - name: Install static analysis tools
        run: dotnet tool install --global dotnet-format

      - name: Run static code analysis
        run: dotnet format --verify-no-changes || true

  merge_check:
    needs: [build_and_test, static_analysis]
    runs-on: ubuntu-latest
    steps:
      - name: Ensure all checks passed before merging
        run: echo "All checks passed!"
