name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x  # або інша стабільна версія

      - name: Set Environment Variables
        run: |
          echo "PROCESSOR_ARCHITECTURE=AMD64" >> $GITHUB_ENV
          echo "MSBUILDDISABLENODEREUSE=1" >> $GITHUB_ENV
          echo "DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1" >> $GITHUB_ENV

      - name: Clear .NET Cache
        run: dotnet nuget locals all --clear

      - name: Restore dependencies
        run: dotnet restore modul.sln

      - name: Build project with MSBuild
       run: |
          & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\MSBuild.exe" modul.sln /p:Configuration=Release /p:Platform="Any CPU" /m
      - name: Run unit tests
        run: dotnet test --no-restore --verbosity normal

  static_analysis:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.201

      - name: Install static analysis tools
        run: dotnet tool install --global dotnet-format

      - name: Run static code analysis
        run: dotnet format --verify-no-changes || true

  merge_check:
    needs: [build_and_test, static_analysis]
    runs-on: ubuntu-latest
    steps:
      - name: Ensure all checks passed before merging
        run: echo "All checks passed!"
